# Generated by Django 3.2.8 on 2021-10-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoriaPK', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='sin nombre', max_length=50, unique=True, verbose_name='Nombre de la categoria')),
                ('descripcion', models.TextField(blank=True, default='sin descripcion', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categoria',
                'db_table': 'tb_categoria',
                'ordering': ['-id_categoriaPK'],
            },
        ),
    ]
