# Generated by Django 3.2.8 on 2021-10-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id_gatewayPK', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(default='s/p', max_length=15, verbose_name='Puerta de Enlace')),
                ('descripcion', models.TextField(blank=True, default='Sin Descripción', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Gateway',
                'verbose_name_plural': 'Gateway',
                'db_table': 'tb_gateway',
                'ordering': ['-id_gatewayPK'],
            },
        ),
    ]
