# Generated by Django 3.2.8 on 2021-10-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='direccion',
            field=models.CharField(default='s/p', max_length=15, unique=True, verbose_name='Puerta de Enlace'),
        ),
    ]
