# Generated by Django 3.2.8 on 2021-10-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='codigo',
            field=models.CharField(default='s/c', max_length=10, unique=True, verbose_name='Código de Agencia'),
        ),
    ]
