# Generated by Django 3.2.8 on 2021-10-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccionip',
            fields=[
                ('id_direccionPK', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(default='Sin asignar', max_length=15, unique=True, verbose_name='Ingrese la dirección IP')),
                ('descripcion', models.TextField(blank=True, default='sin descripción', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direccion',
                'db_table': 'tb_direccionip',
                'ordering': ['-id_direccionPK'],
            },
        ),
    ]
