# Generated by Django 3.2.8 on 2021-12-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccionip', '0002_alter_direccionip_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionip',
            name='estado',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
