# Generated by Django 3.2.8 on 2021-10-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direccionip', '0001_initial'),
        ('categoria', '0001_initial'),
        ('agencia', '0001_initial'),
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id_activoPK', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='s/n', max_length=150, unique=True, verbose_name='Nombre del Activo')),
                ('descripcion', models.TextField(blank=True, default='sin descripcion', verbose_name='Descripción del Activo')),
                ('id_agenciaFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agencia.agencia')),
                ('id_categoriaFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.categoria')),
                ('id_direccionipFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='direccionip.direccionip')),
                ('id_gatewayFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gateway.gateway')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activo',
                'db_table': 'tb_activo',
                'ordering': ['-id_activoPK'],
            },
        ),
    ]
