# Generated by Django 3.2.8 on 2021-10-22 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direccionip', '0002_alter_direccionip_options'),
        ('activo', '0002_alter_activo_id_direccionipfk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='id_direccionipFK',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='direccionip.direccionip'),
        ),
    ]
