# Generated by Django 3.2.8 on 2021-12-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0003_alter_activo_id_direccionipfk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activo',
            options={'ordering': ['id_direccionipFK'], 'verbose_name': 'Activo', 'verbose_name_plural': 'Activo'},
        ),
    ]
